### PR TITLE
Spin-less

### PR DESCRIPTION
**Pull request by amusameh**
Remove the spin wheel from following views **UserProfile**, **Org Profile**, **Search** 
After getting this merged and checking if Harrison is happy with it. then I'll work on applying it on other pages if needed.
relates #463

### CODE REVIEW

**Comment by thejoefriel** [comment]
Hey, I now get some weird lines appear instead of the loading icon: https://www.loom.com/share/834e656ee4134d5fbb3589edcf54d73a

Is that right? Looks a bit odd.

**Comment by amusameh** [comment]
@thejoefriel 
No that's not happening on my end. What browser are you using? Please try to delete the node_modules and package.lock and `npm i` again.

**Comment by amusameh** [comment]
@dupreesi
@thejoefriel  commented on this. It seemed that he had some problem with it.
Did it work fine for you? which browser did you use?

**Comment by dupreesi** [comment]
@amusameh worked for me on chrome and safari and given that no changes were required and the label said awaiting review -> merged it

**Comment by amusameh** [comment]
@dupreesi  sorry that's my fault I should have labeled it with test or something.
It was working fine for me so If you tested it on chrome and safari then everything should be fine.

**Comment by dupreesi** [comment]
@amusameh I think its fine and that joe's problem was rather a setup issue :)

**Pull request merged**
