### PR TITLE
Disable pie chart legend, delete comment for questions

### PR DESCRIPTION
**Pull request by amusameh**
On agency profile: Delete legend and add labels to the chart. #267 
On all (give review orgs) delete the comment icon for question `Overall, would you be happy to use/work with this … again?` #199

### CODE REVIEW

**Comment by thejoefriel** [comment]
Hi @theharrisonmoore we initially removed the legend on the piechart as discussed. However, we can't really make it look the way you've put in wireframes, because as soon as the chunk is very small it can cause formatting issues and the labels on the side make the pie chart itself very small on mobile.

We got to a point of rendering the text inside but this doesn't work fully across all devices either:
image

What we were recommending is something more like this:
image

And we've disabled the legend so clicking it doesn't hard the sections any more (which I think was your main issue) 

Equally hovering or pressing a section will also let them know the section and the number of votes. 

Can you let us know if you're happy with this please?

**Comment by theharrisonmoore** [comment]
@thejoefriel I'm not sure the pie chart is going to work, especially if the text is so small. Now I'm thinking it might be better to render it in the same way we've rendered other data. For example:

Screenshot 2019-06-24 at 12 02 56

Obviously, it would be coloured in purple, not blue. But it might be better? What do you think? Does it represent a lot of extra work for you guys?

**Comment by thejoefriel** [comment]
Sure thing @theharrisonmoore we can do that :) Will look into it now

**Comment by thejoefriel** [comment]
Closing this PR and raising a new one for us to merge this into the develop branch instead: https://github.com/yalla-coop/earwig/pull/404

**Pull request closed without merging**
