### PR TITLE
Simon prio4 backlog chunk2

### PR DESCRIPTION
**Pull request by dupreesi**
relates:
#800 
#795 
#788

### CODE REVIEW

**Comment by dupreesi** [comment]
> * City or town should not be required

@amusameh is this on the main sign up page? strange as this should have been removed by my PR-> can you please try again?

**Comment by amusameh** [comment]
@dupreesi this on the verification page after you sign up not as a worker

**Comment by thejoefriel** [comment]
Hey @dupreesi checking if you've done the final requested change re town? If so I'll review

**Comment by dupreesi** [comment]
@thejoefriel no I was gonna do that tomorrow but feel free to pick up!

**Comment by thejoefriel** [comment]
Nah it's cool, just was wondering if I could review. Will leave for you to sort tomorrow :) And will add a changes requested label so people know there's work to be done on it. Just remove whenever you're ready for it to be reviewed 👍

**Pull request merged**
